### ISSUE TITLE
New releases are missing binaries

### ISSUE THREAD

**Issue by nvx** [miniclip/gonsul#18]
The installation instructions say to use the binaries from the release page. Unfortunately releases after v0.2.1 seem to be missing binaries.

**Comment by paulo-ferraz-oliveira** [comment]
I'm labelling this as a bug since the downloads should have been attached.

**Comment by eduardev** [comment]
@paulo-ferraz-oliveira your latest release didn't include any binaries as @nvx mentioned. And apparently I do not have permissions to manage releases any longer, so can't help much there.

**Comment by paulo-ferraz-oliveira** [comment]
@eduardev, I know it doesn't include the binaries. We'll handle it when there's time, hopefully soon.

**Comment by dmitrikeler** [comment]
Any chance this will be sorted in the near future?

**Comment by ricardopiedade** [comment]
Binaries added to release 0.3.0
