### ISSUE TITLE
No support for numeric values in YAML files

### ISSUE THREAD

**Issue by juan-castrillon** [miniclip/gonsul#35]
Hello! I am trying to use gonsul to store values from a YAML file into consul KV. Given the following structure:
```
out/
└── deployments
    └── environments
        └── production.yaml
```
where `production.yaml` looks like:
```yaml
list1: value1,value2
port1: 7777
url1: https://some.url
url2: other.url.com
url3: yet-another.url.com
list2: value3,value4
ip1: 10.2.3.5
port2: 36482
```

However, when running gonsul with the following command:
```
./gonsul --strategy=DRYRUN --repo-root=out --consul-url=http://localhost:28500 --expand-yaml=true --input-ext=yaml --allow-deletes=skip
```
results in only the non numeric values (all except for `port1` and `port2`) to be added to the operations:
```
+--+-------+----------+----------------+-------------+-------------------------------------------+
|  | BATCH | OP INDEX | OPERATION NAME | CONSUL VERB |                   PATH                    |
+--+-------+----------+----------------+-------------+-------------------------------------------+
|  | 1     | 0        | INSERT         | set         | deployments/environments/production/url2  |
|  | 1     | 1        | INSERT         | set         | deployments/environments/production/url3  |
|  | 1     | 2        | INSERT         | set         | deployments/environments/production/list2 |
|  | 1     | 3        | INSERT         | set         | deployments/environments/production/ip1   |
|  | 1     | 4        | INSERT         | set         | deployments/environments/production/list1 |
|  | 1     | 5        | INSERT         | set         | deployments/environments/production/url1  |
+--+-------+----------+----------------+-------------+-------------------------------------------+
```
If I make port values strings instead of numeric (i.e `port1: "7777"` and `port2: "36482"`) then it works as expected
 
```
+--+-------+----------+----------------+-------------+-------------------------------------------+
|  | BATCH | OP INDEX | OPERATION NAME | CONSUL VERB |                   PATH                    |
+--+-------+----------+----------------+-------------+-------------------------------------------+
|  | 1     | 0        | INSERT         | set         | deployments/environments/production/list1 |
|  | 1     | 1        | INSERT         | set         | deployments/environments/production/port1 |
|  | 1     | 2        | INSERT         | set         | deployments/environments/production/url1  |
|  | 1     | 3        | INSERT         | set         | deployments/environments/production/url2  |
|  | 1     | 4        | INSERT         | set         | deployments/environments/production/url3  |
|  | 1     | 5        | INSERT         | set         | deployments/environments/production/list2 |
|  | 1     | 6        | INSERT         | set         | deployments/environments/production/ip1   |
|  | 1     | 7        | INSERT         | set         | deployments/environments/production/port2 |
+--+-------+----------+----------------+-------------+-------------------------------------------+
```

Is there no support for numeric values in YAML or is this undesired behavior?

I am working with `Gonsul version: v1.0.0-7-ge0f9a4`

Thank you in advance for your response :smiley:

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @juan-castrillon.

Can you tell us the exact tag/commit you're pulling? I'm not sure what that version represents.

Also, FYI, YML does "support" numeric values, though, for example when you specify a number like 14.0, depending on the interpreter that can be an integer (14), a float (14.0) or a string ("14.0").

**Comment by juan-castrillon** [comment]
Hello @paulo-ferraz-oliveira . Thanks for the quick response.

I just grabbed the output of `gonsul -v`. But the release I am using is the latest one https://github.com/miniclip/gonsul/releases/tag/v1.0.1

Thank you for the clarification. As mentioned, I am not sure if what I found is undesired behavior, or just me not completely understanding. However, the docs do mention

```
All the numeric values will obviously be inserted into consul as strings
```

So I assume that numeric values in YAML files should also go into consul (as strings), which does not seem to be the case

**Comment by paulo-ferraz-oliveira** [comment]
> I just grabbed the output of gonsul -v

Oh, I see.

What threw me off was:
1. that's not the latest code, that it is the latest **tagged** code,
2. I don't know where that `-7-g` is coming from, but I will pull request to fix it 😄

**Comment by paulo-ferraz-oliveira** [comment]
So, yeah, `-g` is added by Git and that `7` is the "distance" from the tag being shown (locally I get `10`).

**Comment by paulo-ferraz-oliveira** [comment]
(this'll be the one fixing the "version issue")

As for the behaviour you specifically ask for I'll ask internally and try to get that to you.

**Comment by Chinikins** [comment]
If someone could take a look at this PR for this issue: https://github.com/miniclip/gonsul/pull/44 would be much appreciated

**Comment by fabiomsouto** [comment]
This is now merged and we'll generate a release soon. Thanks!

**Comment by Chinikins** [comment]
much appreciated, thank you!
