### ISSUE TITLE
JSON validation not working

### ISSUE THREAD

**Issue by nvx** [miniclip/gonsul#6]
The readme states `Also, .json files are treated and validated as valid JSON, and inserted into Consul pretty formatted.`

This is a really useful feature. We tried creating an invalid json file and ran gonsul in dry-run mode but it did not indicate any error in the output and returned a success error code (0).

Is this feature dependent on expand json being enabled? Or does it maybe not function in dry run mode?

We are checking out from git ourselves and specifying a --repo-root to point to that location rather than using Gonsul to do this if it makes a difference.

**Comment by eduardev** [comment]
Hey @nvx 

Indeed, JSON validation only happens when using `expand-json` flag. 
Maybe this could be changed so we would always validate JSON. 
Would it be a nice feature in your opinion?

**Comment by eduardev** [comment]
It actually says in the documentation `JSON` files would be validated no matter what, and it's an easy fix. Will mark this as a bug, and will fix it ASAP.

Thanks @nvx

**Comment by eduardev** [comment]
fixed on 90f1a979ebc9823fe712d3367130948c68e22e9d
Also, created new release with new binary files.
Closing ticket
